### PR TITLE
revert(installer): use `vim.o.sh` instead of `'sh'`

### LINKED ISSUE #199: Fails in fish shell
```
Configuring luarocks failed.                                                                                  
stderr: configure (line 5): Unsupported use of '='. In fish, please use 'set prefix "/usr/local"'.            
prefix="/usr/local"                                                                                           
^~~~~~~~~~~~~~~~~~^                                                                                           
warning: Error while reading file configure                                                                   
                                                                                                              
                           
```

### PR DESCRIPTION
**Pull request by gptlang**
Fixes #199 

Tested on Fedora 39 with `NVIM v0.10.0-dev+2606-gc0549b9c4`

### CODE REVIEW

**Review by mrcjkb — APPROVED** [review]
Thanks.

This breaks the installer for Windows (see #166).
But using the configure script on Windows might not be the best idea anyway.

**Comment by mrcjkb** [comment]
I'll try to come up with a proper solution for Windows today, so I'll wait with merging for now.

**Comment by vhyrro** [comment]
This might be a risky thing to attempt, as we can't confirm that the binary will be executable on the target filesystem. When I tested (Arch), I get a "configure is not executable" error. I do think that we should use `sh` instead of `vim.o.sh` however to make sure we're running a POSIX-compatible shell :)

**Comment by gptlang** [comment]
> This might be a risky thing to attempt, as we can't confirm that the binary will be executable on the target filesystem. When I tested (Arch), I get a "configure is not executable" error. I do think that we should use `sh` instead of `vim.o.sh` however to make sure we're running a POSIX-compatible shell :)

Yeah that makes sense to me. Would it make sense to hard code `/bin/sh` or `/bin/env sh`?

**Comment by mrcjkb** [comment]
> > This might be a risky thing to attempt, as we can't confirm that the binary will be executable on the target filesystem. When I tested (Arch), I get a "configure is not executable" error. I do think that we should use `sh` instead of `vim.o.sh` however to make sure we're running a POSIX-compatible shell :)
> 
> Yeah that makes sense to me. Would it make sense to hard code `/bin/sh` or `/bin/env sh`?

I believe `/bin/sh` (or just `sh`) is fine. `/usr/bin/env` is more commonly used for `bash` (which is less commonly available in `/bin`.

**Comment by NTBBloodbath** [comment]
> > > This might be a risky thing to attempt, as we can't confirm that the binary will be executable on the target filesystem. When I tested (Arch), I get a "configure is not executable" error. I do think that we should use `sh` instead of `vim.o.sh` however to make sure we're running a POSIX-compatible shell :)
> > 
> > Yeah that makes sense to me. Would it make sense to hard code `/bin/sh` or `/bin/env sh`?
> 
> I believe `/bin/sh` (or just `sh`) is fine. `/usr/bin/env` is more commonly used for `bash` (which is less commonly available in `/bin`.

I think using `/usr/bin/env sh` would be best. It is the best way to maintain compatibility with any shell even in scripts for BSD systems iirc, I would go with `/bin/sh` but I think that would break on certain systems like Alpine, which is an edge case but it's good to keep it in mind

**Comment by mrcjkb** [comment]
> > > > This might be a risky thing to attempt, as we can't confirm that the binary will be executable on the target filesystem. When I tested (Arch), I get a "configure is not executable" error. I do think that we should use `sh` instead of `vim.o.sh` however to make sure we're running a POSIX-compatible shell :)
> > > 
> > > 
> > > Yeah that makes sense to me. Would it make sense to hard code `/bin/sh` or `/bin/env sh`?
> > 
> > 
> > I believe `/bin/sh` (or just `sh`) is fine. `/usr/bin/env` is more commonly used for `bash` (which is less commonly available in `/bin`.
> 
> I think using `/usr/bin/env sh` would be best. It is the best way to maintain compatibility with any shell even in scripts for BSD systems iirc, I would go with `/bin/sh` but I think that would break on certain systems like Alpine, which is an edge case but it's good to keep it in mind

That only matters with `bash`, not `sh`. 

https://stackoverflow.com/questions/53116226/what-is-the-recommended-posix-sh-shebang

**Review by mrcjkb — APPROVED** [review]

**Comment by mrcjkb** [comment]
Reverts https://github.com/nvim-neorocks/rocks.nvim/commit/54b67cec53f4152c85fb8f7b77a939514b5f78a5

**Pull request merged**
