### PR TITLE
fix(sync): prevent luarocks install tree race conditions

### LINKED ISSUE #61: [Bug] `Rocks sync` should not invoke `luarocks [install|uninstall|update]` concurrently
This leads to partial uninstalls

To reproduce:

- Install a bunch of plugins.
- Remove all plugins from `rocks.toml`.
- Run `Rocks sync`.
- Wait for it to finish.
- Run `Rocks sync` again.

Expected behaviour:

- Progress message says everything is in sync.

Actual behaviour:

- An error message is displayed, saying the rockspec of a previously pruned plugin can\t be found.

This appears to be because of an incomplete uninstall.

Excample:

```
Error executing vim.schedule lua callback: ...pack/myNeovimPackages/start/rocks.nvim/lua/nio/tasks.lua:95: Async task failed without callback: The
coroutine failed with this message:
...ck/myNeovimPackages/start/rocks.nvim/lua/nio/control.lua:107:
Error: Could not load rockspec file /home/mrcjk/.local/share/nvimrocks/rocks/lib/luarocks/rocks-5.1/haskell-snippets.nvim/1.4.2-1/haskell-snippets.
nvim-1.4.2-1.rockspec (/home/mrcjk/.local/share/nvimrocks/rocks/lib/luarocks/rocks-5.1/haskell-snippets.nvim/1.4.2-1/haskell-snippets.nvim-1.4.2-1.
rockspec: No such file or directory)

stack traceback:
        [C]: in function 'error'
        ...ck/myNeovimPackages/start/rocks.nvim/lua/nio/control.lua:107: in function 'wait'
        ...ck/myNeovimPackages/start/rocks.nvim/lua/rocks/state.lua:112: in function 'rock_dependencies'
        ...NeovimPackages/start/rocks.nvim/lua/rocks/operations.lua:275: in function <...NeovimPackages/start/rocks.nvim/lua/rocks/operations.lua:1
54>
stack traceback:
        [C]: in function 'error'
        ...pack/myNeovimPackages/start/rocks.nvim/lua/nio/tasks.lua:95: in function 'close_task'
        ...pack/myNeovimPackages/start/rocks.nvim/lua/nio/tasks.lua:117: in function 'cb'
        ...pack/myNeovimPackages/start/rocks.nvim/lua/nio/tasks.lua:181: in function 'waiter'
        ...ck/myNeovimPackages/start/rocks.nvim/lua/nio/control.lua:81: in function 'wake'
        ...ck/myNeovimPackages/start/rocks.nvim/lua/nio/control.lua:99: in function 'set_error'
        ...ck/myNeovimPackages/start/rocks.nvim/lua/rocks/state.lua:106: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### PR DESCRIPTION
**Pull request by mrcjkb**
Fixes #61

### CODE REVIEW

**Comment by mrcjkb** [comment]
Something seems to be completely broken with the `user_rocks` in this branch.
`vim.print` prints out `{ "__path" }`.

**Comment by mrcjkb** [comment]
> Something seems to be completely broken with the `user_rocks` in this branch. `vim.print` prints out `{ "__path" }`.

Fixed it in #60.

I accidentally replaced `toml` with `toml-edit` as the parser.

**Comment by mrcjkb** [comment]
-[ ] #62  needs to be applied to the versions checked when syncing, too. Or it will attempt to upgrade up-to-date rocks.

**Comment by mrcjkb** [comment]
- [ ] It looks like install/upgrade/downgrade has to be sequential, too.
- [ ] And we should probably implement a locking mechanism to prevent users from spamming sync/install, etc.

**Comment by vhyrro** [comment]
Woopsie...

**Pull request merged**
