### PR TITLE
[FEATURE]: Implement an install script for `rocks.nvim`

### PR DESCRIPTION
**Pull request by vhyrro**
This PR adds a fully working installation process using a remote `:source` command invocation.

While there are still a few rough edges I believe it's a good enough MVP to push into main :)

### CODE REVIEW

**Review by mrcjkb — COMMENTED** [review]
question: Do we need to configure luarocks to use the rocks-binaries so that rocks.nvim can update itself?
Otherwise, users would have to have the rust and C++ toolchains installed, wouldn't they?

**Comment by vhyrro** [comment]
Yep, without the binary rocks users would need to have a modern CPP compiler and rust tool chain. If luarocks can't find the binary rock for the target architecture it'll try compiling instead.

**Review by NTBBloodbath — APPROVED** [review]
LGTM!

**Comment by NTBBloodbath** [comment]
> question: Do we need to configure luarocks to use the rocks-binaries so that rocks.nvim can update itself?
> Otherwise, users would have to have the rust and C++ toolchains installed, wouldn't they?

How could we do that? Since it is the dependencies that we want to extract from rocks-binaries and not the complete package 🤔

**Comment by mrcjkb** [comment]
> > question: Do we need to configure luarocks to use the rocks-binaries so that rocks.nvim can update itself?
> > Otherwise, users would have to have the rust and C++ toolchains installed, wouldn't they?
> 
> How could we do that? Since it is the dependencies that we want to extract from rocks-binaries and not the complete package 🤔

Maybe we have to specify the dependencies separately - or we can add rocks.nvim to the rocks-binaries manifest, but not as a binary. And add a `server` option to the `rocks.toml` settings or something.

**Comment by vhyrro** [comment]
Not sure if I understand the questions being asked here - the server that we configure is is simply the *preferred* server. When luarocks tries to pull in `rocks.nvim`, it notices the dependencies, then first tries to pull from our server before falling back to the regular luarocks manifest. Everything works without interruptions :)

**Comment by mrcjkb** [comment]
> Not sure if I understand the questions being asked here - the server that we configure is is simply the _preferred_ server. When luarocks tries to pull in `rocks.nvim`, it notices the dependencies, then first tries to pull from our server before falling back to the regular luarocks manifest. Everything works without interruptions :)

That's the install script. What about updates? I don't think we specify `--server` for `Rocks sync`?

**Comment by vhyrro** [comment]
Ah you're right. I was certain I also added that, but apparently I didn't. All rocks operations should also pass the `--server` flag

**Comment by mrcjkb** [comment]
I just tried running the installer (from a local file).

- There was a graphical glitch when editing the installation path:

installer

- I was unable to change the `setup_luarocks` option from `true` to `false` (`E21: Cannot make changes, 'modifiable' is off`) and it had a similar graphical glitch.

**Comment by vhyrro** [comment]
Hm, weird. I guess it has to do with some calculations that the installer is making. Let me see if I can fix that.

**Comment by vhyrro** [comment]
Should be fixed now! :D

**Review by mrcjkb — APPROVED** [review]

**Pull request merged**
