### PR TITLE
feat: update remote plugins after install/update

### PR DESCRIPTION
**Pull request by mrcjkb**

### CODE REVIEW

**Review by vhyrro — APPROVED** [review]

**Comment by teto** [comment]
I am curious what was the request asking for it . Note that justin seems to be actively trying to remove remote plugins so maybe this could have been a RocksPostSync hook instead.

**Comment by mrcjkb** [comment]
> I am curious what was the request asking for it . Note that justin seems to be actively trying to remove remote plugins so maybe this could have been a RocksPostSync hook instead.

There wasn't a request. I just realised that remote plugins are still a thing and they typically tell people to put `build = ':UpdateRemotePlugins' ` in their install instructions.
Since the command only needs to be run once after install/update/sync, it doesn't have a significant impact on performance and I see no harm in adding it.

**Comment by teto** [comment]
yes it's a good idea but I saw you were going to release rocks.nvim and I thought I would suggest a more generic event (thought not sure how one would use that) that could survive a breaking change.

**Comment by mrcjkb** [comment]
I think user events could be a good idea.
rocks.nvim extensions could hook into them too.
We could also have events for `RocksFooCachePopulated` or `RocksFooCacheUpdated`, which might be useful for rocks-edit.nvim.

Let's create an issue for it and collect ideas.

**Comment by mrcjkb** [comment]
https://github.com/neovim/neovim/issues/27949

**Pull request merged**
