### PR TITLE
fix(installer/bootstrap): pin luarocks to v3.11.1

### LINKED ISSUE #568: Installation script no longer works
Hello and thank you for the great work you are doing, since a couple of days the installation script does not work for me anymore, before it worked regularly, I used it numerous times before without any problem. I don't know if this is due to some changes made, my system (RHEL) has not been updated in this period so I think we can exclude this as a cause. The same error also occurs when used in a Rocky Linux with lua 5.1 in `~/.local/bin/lua`.
The plugins in the existing configurations work normally.

```bash
cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
```

```bash
ll /usr/bin/lua*
-rwxr-xr-x. 1 root root   23792 17 apr  2023 /usr/bin/lua
-rwxr-xr-x. 1 root root   24472 23 mar  2022 /usr/bin/lua-5.1
-rwxr-xr-x. 1 root root  161472 17 apr  2023 /usr/bin/luac
-rwxr-xr-x. 1 root root  108488 23 mar  2022 /usr/bin/luac-5.1
lrwxrwxrwx. 1 root root       6 27 mag  2023 /usr/bin/luacsplain -> luatex
-rwxr-xr-x. 1 root root    1434  7 mag 22.16 /usr/bin/luarocks
-rwxr-xr-x. 1 root root     916  7 mag 22.16 /usr/bin/luarocks-admin
-rwxr-xr-x. 1 root root 6841832 27 mag  2023 /usr/bin/luatex
```

```bash
ll /usr/local/include/
totale 52
-rw-r--r--. 1 root root  5777 27 dic  2007 lauxlib.h
-rw-r--r--. 1 root root 22299 11 feb  2008 luaconf.h
-rw-r--r--. 1 root root 11688 13 gen  2012 lua.h
-rw-r--r--. 1 root root   191 23 dic  2004 lua.hpp
-rw-r--r--. 1 root root  1026 27 dic  2007 lualib.h
```

```bash
ll /usr/local/bin/
totale 21928
-rwxr-xr-x. 1 root root   219200 16 ott 09.20 lua
-rwxr-xr-x. 1 root root   151680 16 ott 09.20 luac
-rwxr-xr-x. 1 root root 22076392 11 ott 08.01 nvim
```

```bash
/usr/local/bin/lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

The error in question is as follows:

```bash
Installing rocks.nvim...
Installing rocks.nvim failed:                                                                                 
stderr: /usr/bin/lua-5.1: /run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/persist.lua:25: b
ad argument #1 to 'load' (function expected, got string)                                                      
stack traceback:                                                                                              
^I[C]: in function 'load'                                                                                     
^I/run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/persist.lua:25: in function 'run_file'   
^I/run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/persist.lua:60: in function 'load_into_ta
ble'                                                                                                          
^I/run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/cfg.lua:139: in function 'load_config_fil
e'                                                                                                            
^I/run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/core/cfg.lua:716: in function 'init'          
^I/run/user/1000/luarocks-CB511A84450400/share/lua/5.1/luarocks/loader.lua:21: in main chunk                  
^I[C]: in function 'require'                                                                                  
^I/run/user/1000/luarocks-CB511A84450400/bin/luarocks:9: in main chunk                                        
^I[C]: ?                                                                                                      
                                                                                                              
stdout: 
```

Thank you

### PR DESCRIPTION
**Pull request by mrcjkb**
Should hopefully fix #568.

@ambaradan would you mind testing with the changes in this PR? :pray:

### CODE REVIEW

**Comment by ambaradan** [comment]
error

**Comment by ambaradan** [comment]
I still have a RHEL at home; I will do some tests on that tonight to rule out any error on my part.

**Comment by ambaradan** [comment]
Same thing using `luaver`

```txt
stderr: /home/ambaradan/.luaver/lua/5.1/bin/lua: ...511A84450400/share/lua/5.1/luarocks/core/persist.lua:25: bad argument #1 to '
load' (function expected, got string)
```

**Comment by mrcjkb** [comment]
:thinking: I just tried running the install script (the one on `master`) on NixOS, and did not encounter any issues.

The stack trace in your screenshot is definitely for the current `HEAD` of the `master` branch of luarocks (`load` being called in the `luarocks.core.persist` module on line 25).
On the `v3.11.1` tag, there's no `load` call on that line.

Merging this PR, as it makes sense to pin the version anyway.
After that, you can try again with the regular install script.

**Comment by ambaradan** [comment]
@mrcjkb The fix solved the problem, now the installation works again even on RHEL, many thanks.

**Pull request merged**
