### PR TITLE
feat(commands): fuzzy completions for `:Rocks install [rock]`

### PR DESCRIPTION
**Pull request by mrcjkb**
Uses `fzy` to implement fuzzy completions for rocks in the `:Rocks install` command.

Manual test:

```console
nix run .#neovim-with-rocks
```
```vim
:Rocks ill<TAB>
```

Completes to `:Rocks install`.

```vim
:Rocks install norg<TAB>
```

Shows `neorg` as the first completion result.

Install `neorg` if not installed.

```vim
:Rocks prune norg<TAB>
```

Shows `neorg` as the first completion result.

### CODE REVIEW

**Review by NTBBloodbath — COMMENTED** [review]
LGTM, I'll test it in a while! :P

**Comment by mrcjkb** [comment]
Update: Extracted `fuzzy_sort` into a `rocks.fzy` module, and applied it to both `:Rocks install` and `:Rocks prune` commands.

**Review by NTBBloodbath — APPROVED** [review]
Works like a charm on my end, is there something else before we merge this?

**Comment by mrcjkb** [comment]
> Works like a charm on my end, is there something else before we merge this?

All done on my end.

**Pull request merged**
